using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("1.5")]
[assembly: AssemblyFileVersionAttribute("1.5.0.0")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) Louis DeJardin 2008-2011")]
[assembly: AssemblyProductAttribute("Spark")]
[assembly: AssemblyCompanyAttribute("Louis DeJardin")]
[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyInformationalVersionAttribute("1.5.0.0")]
[assembly: SecurityRules(SecurityRuleSet.Level1)]

