using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("1.7")]
[assembly: AssemblyFileVersionAttribute("1.7.4.0")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) Louis DeJardin 2008-2012")]
[assembly: AssemblyProductAttribute("Spark")]
[assembly: AssemblyCompanyAttribute("Louis DeJardin")]
[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyInformationalVersionAttribute("1.7.4.0")]

