# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
       cd src
       dotnet restore spark-ci.slnf
    - name: Build
      run: |
        cd src
        dotnet build --no-restore spark-ci.slnf
    - name: Test
      run: |
        cd src
        dotnet test --no-build --verbosity normal spark-ci.slnf
    - name: Pack
      run: |
        cd src
        dotnet pack spark-pack.slnf
