# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release to NuGet

on:
  release:
    types: [published]

jobs:
  build:
    
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
       cd src
       dotnet restore spark-ci.slnf
    - name: Build
      run: |
        cd src
        dotnet build spark-ci.slnf --no-restore
    - name: Test
      run: |
        cd src
        dotnet test spark-ci.slnf --verbosity normal --no-build  
    - name: Pack
      run: |
        cd src
        dotnet pack spark-pack.slnf --include-symbols --output nupkgs --no-build
    - name: Push to NuGet
      run: |
        cd src/nupkgs
        dotnet nuget push "**/*.nupkg" -s --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json -v
    